"""added role

Revision ID: 17218d474bda
Revises: d90bd29e78f1
Create Date: 2021-09-08 21:15:08.245879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17218d474bda'
down_revision = 'd90bd29e78f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_model', sa.Column('role', sa.String(length=32), server_default='admin', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model', 'role')
    # ### end Alembic commands ###
